name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CLOSURE_TREE_TEST_DATABASE_URL: postgres://closure_tree:closure_tree_pass@localhost:5432/closure_tree_test
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: closure_tree
          POSTGRES_PASSWORD: closure_tree_pass
          POSTGRES_DB: closure_tree_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --all-targets -- -D warnings

      - name: Run tests
        run: cargo test
